# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ecran2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1522, 710)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.contextContent = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.contextContent.setFont(font)
        self.contextContent.setObjectName("contextContent")
        self.gridLayout.addWidget(self.contextContent, 0, 0, 1, 1)
        self.content = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("MS Mincho")
        font.setPointSize(80)
        font.setBold(False)
        font.setWeight(80)
        self.content.setFont(font)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setLineWidth(0)
        self.content.setTextFormat(QtCore.Qt.AutoText)
        self.content.setScaledContents(True)
        self.content.setAlignment(QtCore.Qt.AlignCenter)
        self.content.setWordWrap(True)
        self.content.setObjectName("content")
        self.gridLayout.addWidget(self.content, 1, 0, 1, 2)
        self.nbrWrap = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.nbrWrap.setFont(font)
        self.nbrWrap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nbrWrap.setObjectName("nbrWrap")
        self.gridLayout.addWidget(self.nbrWrap, 2, 1, 1, 1)
        self.content.setMargin(100)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.contextContent.setText(_translate("Form", "         Genesisy 2 : 5 ,"))
        self.content.setText(_translate("Form", "Lorem Ipsum est tout simplement un faux texte de l’industrie de l’imprimerie et de la composition. Lorem Ipsum est le texte factice standard de l\'industrie depuis les années 1500, lorsqu\'un imprimeur inconnu a pris une galerie de caractères et l\'a brouillée pour en faire un livre de spécimens de caractères. Il a survécu non seulement à cinq siècles, mais aussi au saut vers la composition électronique, restant essentiellement inchangé. Il a été popularisé dans les années 1960 avec la sortie de feuilles Letraset contenant des passages de Lorem Ipsum, et plus récemment avec des logiciels de publication assistée par ordinateur comme Aldus PageMaker incluant des versions de Lorem Ipsum."))
        self.nbrWrap.setText(_translate("Form", "2/5           "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
